### ISSUE TITLE
Parse genotype from NCBI data

### ISSUE THREAD

**Issue by kimandrews** [nextstrain/measles#16]
[As discussed](https://github.com/nextstrain/measles/pull/10#discussion_r1473730032), the Virus Name metadata column output by NCBI Datasets sometimes includes genotype info for measles, and it could be useful to visualize this info on the phylogeny in auspice. This could be accomplished by parsing out the genotype info from the metadata using a custom script.

**Comment by joverlee521** [comment]
We (myself, @kimandrews, and @j23414) briefly discussed this in our chat today.

I recommended finding more details about the genotype info for measles and trying to see if there are official "definitions" for each genotype. If so, we can use them to create a Nextclade dataset that can assign the genotype info to sequences rather than depending on annotations from NCBI.

**Comment by kimandrews** [comment]
Done in https://github.com/nextstrain/measles/pull/26/commits/cce8b3c2722166de0866dfbeb63467d9ab918dfb
